#!/usr/bin/env bash
set -euo pipefail

fail() {
    printf 'immich-auto-cast update: %s\n' "$*" >&2
    exit 1
}

[[ $EUID -eq 0 ]] || fail "run this command with sudo"

INSTALL_CONFIG="/etc/immich-auto-cast-install.conf"
if [[ -f "$INSTALL_CONFIG" ]]; then
    # This file is generated by the installer and writable only by root.
    source "$INSTALL_CONFIG"
fi

: "${CAST_IMMICH_APP_DIR:?missing application directory}"
: "${CAST_IMMICH_APP_USER:?missing service user}"
: "${CAST_IMMICH_APP_HOME:?missing service user home}"
: "${CAST_IMMICH_UV_BIN:?missing uv path}"
: "${CAST_IMMICH_SERVICE:?missing service name}"

[[ -d "$CAST_IMMICH_APP_DIR/.git" ]] || fail "$CAST_IMMICH_APP_DIR is not a Git checkout"
[[ -x "$CAST_IMMICH_UV_BIN" ]] || fail "uv is not executable at $CAST_IMMICH_UV_BIN"

printf 'Pulling the latest revision...\n'
sudo -u "$CAST_IMMICH_APP_USER" git -C "$CAST_IMMICH_APP_DIR" pull --ff-only

printf 'Synchronizing locked dependencies...\n'
sudo -u "$CAST_IMMICH_APP_USER" env HOME="$CAST_IMMICH_APP_HOME" \
    "$CAST_IMMICH_UV_BIN" sync --project "$CAST_IMMICH_APP_DIR" --locked --no-dev

printf 'Restarting %s...\n' "$CAST_IMMICH_SERVICE"
systemctl restart "$CAST_IMMICH_SERVICE.service"
systemctl --no-pager --full status "$CAST_IMMICH_SERVICE.service"
